local opt = vim.opt

opt.laststatus = 3
opt.guicursor = ""
opt.termguicolors = true
opt.number = true
opt.relativenumber = true
opt.tabstop = 4
opt.softtabstop = 4
opt.scrolloff = 8
opt.shiftwidth = 4
opt.expandtab = true
opt.smartindent = true
opt.timeoutlen = 250
opt.ttimeoutlen = 0
opt.swapfile = false
opt.backup = false
opt.undofile = true
opt.signcolumn = "yes"
opt.cursorline = true
opt.cursorlineopt = "number"
